name: "NASA Rocket Science"
description: ""

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Jekyll Bootstrap
tagline: Site Tagline
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://username.github.io

#url: "http://nasa-rocket-science.github.io/"
url: "http://smartin41.github.io/"
#uncomment the following for local testing
#url: "http://localhost:4000/"

paginate: 5
paginate_path: "news/page:num"
timezone: "America/New_York"

exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

markdown: kramdown

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

highlighter: rouge

# Custom vars
#current_version:  1.0
#repo:             https://github.com/sunpy/sunpy
#install_instructions: http://docs.sunpy.org/en/stable/guide/installation/